repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --all
        language: system
        types_or: [rust, toml]
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        entry: cargo test --all --locked
        language: system
        pass_filenames: false