[package]
name = "datadoggo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-postgres = "0.7"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
rss = "2.0"
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tokio-test = "0.4"
